# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

# TODO Rust builds on stable by default, this can be
# overridden on a case by case basis down below.

env:
  global:
    # TODO Update this to match the name of your project.
    - CRATE_NAME=sfz
    - RUST_BACKTRACE: full

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    # Ignore all 32-bit targets.
    # Stable channel.
    # - env: TARGET=i686-unknown-linux-gnu
    # - env: TARGET=i686-unknown-linux-musl
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    # - env: TARGET=i686-apple-darwin
    #   os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Beta channel.
    # - env: TARGET=i686-unknown-linux-gnu
    #   rust: beta
    # - env: TARGET=i686-unknown-linux-musl
    #   rust: beta
    # - env: TARGET=x86_64-unknown-linux-gnu
    #   rust: beta
    - env: TARGET=x86_64-unknown-linux-musl
      rust: beta
    # - env: TARGET=i686-apple-darwin
    #   os: osx
    #   rust: beta
    # - env: TARGET=x86_64-apple-darwin
    #   os: osx
    #   rust: beta

    # Nighly channel.
    # Disable to reduce CI time
    # - env: TARGET=i686-unknown-linux-gnu
    #   rust: nightly
    # - env: TARGET=i686-unknown-linux-musl
    #   rust: nightly
    # - env: TARGET=x86_64-unknown-linux-gnu
    #   rust: nightly
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    # - env: TARGET=i686-apple-darwin
    #   os: osx
    #   rust: nightly
    # - env: TARGET=x86_64-apple-darwin
    #   os: osx
    #   rust: nightly

before_install:
  - set -e
  - rustup self update
  - |
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        PR_FIRST=$(curl -s https://github.com/${TRAVIS_REPO_SLUG}/pull/${TRAVIS_PULL_REQUEST}.patch | head -1 | grep -o -E '\b[0-9a-f]{40}\b' | tr -d '\n')
        TRAVIS_COMMIT_RANGE=$PR_FIRST^..${TRAVIS_COMMIT}
      fi
      git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '\.md$|^(docs|\.github)/|\.appveyor.yml$' || {
        echo "Only docs were updated, stopping build process."
        travis_terminate 0
      }

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh

after_script: set +e

before_deploy:
  - sh ci/before_deploy.sh

deploy:
  # TODO update `api_key.secure`
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789
  # - Paste the output down here
  api_key:
    secure: Cpf5+csJdoH8MzR2CJ1WnkRF8aU+292lyukLS9yLJq8rujZZVu8fGxS1IlGSWaQEEJJKygbRIaE02q5BuzA4xfwqOVXcfRiUxVBaeIISXYTE+a/6U7mMw5UAPncUEsz5dNj+SM4eemJ+xpgZIZcgbWF8w9rKlTQ0qBjS1Hk4iLfe/UTYXdhYcibTnfH/2xyeoApwJHN3TWcGITcWtuQ8Lvp6CazHncyJdhqhf1imEbZb4Mw/crzgk8Dv4nw7Dijf/wLTNAhhsZfaSJJsCQyUYoc7uk+ivbxy+G/Ndw9X9GizdYIKI9itnDEBSirANZF1RDW7dlJw+7RJGhsA9Tsj1IkiepVdVQC6IzVm4Jpzx+9d66zWUQG2HsFkscICcmNjnExtaHt3h+Akkdj8gQOmiiEXsivkwt1vlEE/iVcFbX/6TMiH0iHCNMbbb9fh7GY13U1Ql8evDGmQ8w8OP69bmULH3wuWXc7Z9TpEE2uhcs/F69sgRuJLy8G8Dn628SPpJ01NPEQHWtc2+e+ntoRyyvBynSZJzGWRlPvgtxFMVqg52sabduCaH7LGjEt/Sx7V3EjDZ16PCsRwUPwlKHLogRBhm2EcWc+pF9y8JV96CPbiVEESTcBYF3MG7VjibzjCQ5TiMuOebKw+Uiqkiy9M4Ph+SW6iE378rfMa2gLPxKE=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    # TODO Here you can pick which targets will generate binary releases
    # In this example, there are some targets that are tested using the stable
    # and nightly channels. This condition makes sure there is only one release
    # for such targets and that's generated using the stable channel
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v?\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never
