[package]
name = "serve"
version = "0.1.0"
authors = ["Weihang Lo <weihanglotw@gmail.com>"]

[dependencies]
clap = "2.29"
futures = "0.1"
hyper = "0.11"
mime_guess = "2.0.0-alpha"
percent-encoding = "1.0"
tera = "0.11"
unicase = "2.1" # Dependency of Hyper CORS headers
