[package]
name = "sfz"
version = "0.1.2"
authors = ["Weihang Lo <me@weihanglo.tw>"]
description = "A simple static file serving command-line tool."
documentation = "https://github.com/weihanglo/sfz"
homepage = "https://github.com/weihanglo/sfz"
repository = "https://github.com/weihanglo/sfz"
readme = "README.md"
keywords = ["static", "file", "server", "http", "cli"]
categories = ["command-line-utilities", "web-programming::http-server"]
exclude = ["HomebrewFormula"]
license = "MIT/Apache-2.0"
edition = "2018"

[badges]
appveyor = { repository = "weihanglo/sfz" }
travis-ci = { repository = "weihanglo/sfz" }

[dependencies]
# Command-line
clap = { version = "2.33", default-features = false }
# Server
tokio = { version = "0.2", features = ["rt-core", "tcp", "macros"] }
futures = { version = "0.1", features = ["use_std"], default-features = false }
hyper = "0.13"
mime_guess = "2.0"
percent-encoding = "2.1"
unicase = "2.6" # Dependency for Hyper CORS headers
# Compression
brotli = "3"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }
# Rendering
tera = "1"
serde = { version = "1.0", features = ["derive"] } # For tera serializing variables to template.
ignore = "0.4" # Respect to .gitignore while listing directories.
# Logging
chrono = "0.4"

[dev-dependencies]
tempdir = "0.3"

[profile.dev]
codegen-units = 2
incremental = true

[profile.release]
lto = true
panic = "abort"
