[package]
name = "sfz"
version = "0.0.1"
authors = ["Weihang Lo <weihanglotw@gmail.com>"]
description = "A simple static file serving command-line tool."
repository = "https://github.com/weihanglo/sfz"
readme = "README.md"
keywords = ["cli", "server", "file", "directory", "static"]
categories = ["command-line-utilities", "web-programming"]
license = "Apache-2.0/MIT"

[badges]

appveyor = { repository = "weihanglo/sfz" }
travis-ci = { repository = "weihanglo/sfz" }
# codecov = { repository = "weihanglo/sfz" }

[dependencies]
# Command-line
clap = "2.29"

# Server
futures = "0.1"
hyper = "0.11"
mime_guess = "2.0.0-alpha"
percent-encoding = "1.0"
unicase = "2.1" # Dependency for Hyper CORS headers

# Compression
brotli = "1.1"
flate2 = { version = "1.0", features = ["rust_backend"], default-features = false }

# Rendering
tera = "0.11"
serde = "1.0" # For tera serializing variables to template.
serde_derive = "1.0"
ignore = "0.4" # Respect to .gitignore while listing directories.

# Miscellaneous
