name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: ['*']

env:
  RUST_BACKTRACE: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup update stable && rustup default stable
    - run: rustup component add rustfmt
    - run: cargo fmt -- --check

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          rust: stable
          other: i686-unknown-linux-gnu
        - os: ubuntu-latest
          rust: nightly
          other: i686-unknown-linux-gnu
        - os: macos-latest
          rust: stable
          other: x86_64-apple-ios
        - os: windows-latest
          rust: stable-msvc
          other: i686-pc-windows-msvc
        - os: windows-latest
          rust: nightly-gnu
          other: i686-pc-windows-gnu

    steps:
    - uses: actions/checkout@v2
    - run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
    - run: rustup target add ${{ matrix.other }}
    - run: cargo test
